"""empty message

Revision ID: 58c404b88714
Revises: c374ef486531
Create Date: 2019-07-12 14:30:29.237459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c404b88714'
down_revision = 'c374ef486531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'status')
    # ### end Alembic commands ###
