"""empty message

Revision ID: 80050203160f
Revises: 2e1fe5ef8a1c
Create Date: 2019-07-09 17:39:29.051409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80050203160f'
down_revision = '2e1fe5ef8a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'auth', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='foreignkey')
    # ### end Alembic commands ###
