"""empty message

Revision ID: c374ef486531
Revises: 80050203160f
Create Date: 2019-07-11 15:35:47.011249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c374ef486531'
down_revision = '80050203160f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('role', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'status')
    op.drop_column('auth', 'status')
    # ### end Alembic commands ###
